name: Tests

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "develop"

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

      - name: Run Jest Tests
        env:
          JWT_LIFETIME: ${{ secrets.JWT_LIFETIME }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          PORT: ${{ secrets.PORT }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: npm run test:coverage
