name: Tests

on:
  push:
  pull_request:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: v18.17.1

      - name: Install Dependencies
        run: npm ci

      - name: Run Jest Tests
        env:
          JWT_LIFETIME: ${{ secrets.JWT_LIFETIME }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          PORT: ${{ secrets.PORT }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          github-token: ${{ github.token }}
        run: npm run test:coverage

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.2.3
        with:
          github-token: ${{ github.token }}
        env:
          COVERALLS_REPO_TOKEN: CgqnJ6Ze3FSrDAtgOiO6kBKvY8CYFqTjL
