name: Run tests

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm ci
      - name: Run tests
        env:
          JWT_LIFETIME: 30d
          JWT_SECRET_KEY: MyNameIsMurenziPaterneAndILoveProgramming
          PORT: 3000
          MONGO_URI : mongodb+srv://mr3nz1:w1gZCPocWbJKu85f@cluster0.6pjqgro.mongodb.net/
        run: npm test
