name: 'Test Report'
on:
  workflow_run:
    workflows: ['Tests']                     
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
    build-test:
        name: Build & Test
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3     
          - run: npm ci         
          - run: npm test          
          - name: Test Report
            uses: actions/upload-artifact@v2
            if: always()                  
            with:
              name: test-results          
              path: ./coverage/clover.xml       

# name: Tests

# on:
#   push:
#     branches:
#       - "develop"
#   pull_request:
#     branches:
#       - "develop"

# permissions:
#   contents: read
#   actions: read
#   checks: write

# jobs:
#   tests:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Setup Node
#         uses: actions/setup-node@v2
#         with:
#           node-version: 20

#       - name: Install Dependencies
#         run: npm ci

#       - name: jest-tests
#         uses: actions/upload-artifact@v3
#         if: success() || failure()
#         with:
#           name: test-results
#           path: ./coverage/clover.xml
#         env:
#           JWT_LIFETIME: ${{ secrets.JWT_LIFETIME }}
#           JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
#           PORT: ${{ secrets.PORT }}
#           MONGO_URI: ${{ secrets.MONGO_URI }}
#       - run: npm test
