name: 'Test Report'
on:
  workflow_run:
    workflows: ['Tests']                     
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
    build-test:
        name: Build & Test
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3     
          - run: npm ci                   
          - name: Test Report
            uses: actions/upload-artifact@v2
            if: always()                  
            with:
              name: test-results          
              path: ./coverage/clover.xml       